### PR TITLE
Add redirect route /mobile to /products

### PR DESCRIPTION
**Pull request by kirubarajan**

### CODE REVIEW

**Comment by kirubarajan** [comment]
Is there a nicer way to catch trailing slashes in routes (i.e. regex or the like)? Assigning the JS gods to help me out.

**Comment by ajmichaels** [comment]
You could use a regex like /^\/routes(\/.*)?$/ but I think it's fine to do it the way you have it.

**Comment by armic** [comment]
You could use a regex like /^\\/mobile(\\/.*)?$/ but I think it's better to do it the way you have it.

**Comment by kirubarajan** [comment]
Awesome - thanks!

**Pull request merged**
